FROM mongo:4.2

COPY data/genre_all.tar.gz /genre_all.tar.gz

RUN tar -xf genre_all.tar.gz && rm genre_all.tar.gz

CMD mongoimport --uri="mongodb://mongo:27017/government" --collection=genre_all --type=json --file genre_all.json --jsonArray